apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: weather-app
  namespace: argocd
spec:
  project: default
  source:
    path: argocd/projects/overlays/staging
    repoURL: git@github.com:tmayweather/argocd-test.git
    targetRevision: main
    directory:
      recurse: false
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: staging
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true