apiVersion: v1
kind: Service
metadata:
  name: clutch-api
  labels:
    service: clutch-api
    app: clutch-api
    tier: backend
spec:
  ports:
  - port: 8000
    targetPort: 80
    protocol: TCP
  selector:
    service: clutch-api
