apiVersion: apps/v1
kind: Deployment
metadata:
  name: clutch-api
spec:
  replicas: 1
  selector:
    matchLabels:
      service: clutch-api
      app: clutch-api
      tier: backend
  template:
    metadata:
      labels:
        service: clutch-api
        app: clutch-api
        tier: backend
    spec:
      containers:
        - name: clutch-api
          image: tmayweather/clutch-api:v0.1
          ports:
            - containerPort: 8000