apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      service: weather-api
      app: weather-backend
      tier: backend
  template:
    metadata:
      labels:
        app: weather-backend
        tier: backend
    spec:
      containers:
        - name: backend
          image: tmayweather/backend-weather:latest
          ports:
            - containerPort: 8000