apiVersion: apps/v1
kind: Deployment
metadata:
  name: clutch-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      service: clutch-ui
      app: clutch-ui
      tier: frontend
  template:
    metadata:
      labels:
        service: clutch-ui
        app: clutch-ui
        tier: frontend
    spec:
      containers:
        - name: clutch-ui
          image: tmayweather/clutch-ui:v.01
          ports:
            - containerPort: 80
