apiVersion: v1
kind: Service
metadata:
  name: weather-frontend
  labels:
    app: weather-frontend
    service: weather-ui
    tier: frontend
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: weather-frontend
    service: weather-ui
    tier: frontend
