apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clutch-app-dev
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: clutch-ui=tmayweather/clutch-ui:latest, clutch-api=tmayweather/clutch-api:latest
    argocd-image-updater.argoproj.io/clutch-ui.update-strategy: digest
    argocd-image-updater.argoproj.io/clutch-api.update-strategy: digest
    argocd-image-updater.argoproj.io/clutch-ui.allow-tags: regexp:^(sha-)?[0-9a-f]{7,}$
    argocd-image-updater.argoproj.io/myimage.allow-tags: regexp:^(sha-)?[0-9a-f]{7,}$
    argocd-image-updater.argoproj.io/write-back-method: git
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: argocd/projects/overlays/dev
    repoURL: git@github.com:tmayweather/argocd-test.git
    targetRevision: main
    directory:
      recurse: false
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true