apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clutch-app-dev
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: myimage=tmayweather/clutch-ui
    argocd-image-updater.argoproj.io/myimage.update-strategy: latest
    argocd-image-updater.argoproj.io/myimage.allow-tags: regexp:^[0-9a-f]{7}$
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: argocd/projects/overlays/dev
    repoURL: git@github.com:tmayweather/argocd-test.git
    targetRevision: main
    directory:
      recurse: false
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true