apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namePrefix: dev
namespace: dev
patchesStrategicMerge:
- backend-deployment.yaml
- frontend-deployment.yaml
commonLabels:
  env: dev

