apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namePrefix: dev
namespace: dev
patchesStrategicMerge:
- backend-deployment.yaml
- frontend-deployment.yaml
commonLabels:
  env: dev
images:
- name: backend
  newName: tmayweather/clutch-api
  newTag: sha-dfbcabf
- name: frontend
  newName: tmayweather/clutch-ui
  newTag: sha-dfbcabf
- name: tmayweather/clutch-api
  newTag: sha-2ec41ce
- name: tmayweather/clutch-ui
  newTag: sha-2ec41ce
