apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namePrefix: dev
namespace: dev
patchesStrategicMerge:
- backend-deployment.yaml
- frontend-deployment.yaml
commonLabels:
  env: dev
images:
- name: tmayweather/clucth-api
  newTag: sha-3691264
- name: tmayweather/clutch-api
  newTag: sha-f5f501d
- name: tmayweather/clutch-ui
  newTag: sha-f5f501d
