apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: apps/argocd
spec:
  project: default
  sources:
  - repoURL: 'https://argoproj.github.io/argo-helm'
    chart: argo-cd
    targetRevision: 5.52.1
    helm:
      valueFiles:
        - $values/kubernetes/apps/argocd/app/values.yaml
  - repoURL: 'https://github.com/tmayweather/argocd-test.git'
    targetRevision: main
    path: apps/argocd
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true