apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: apps/ # it watches over the apps directory
    repoURL: git@github.com:tmayweather/argocd-test.git
    targetRevision: main
    directory:
      recurse: false
  destination:
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    syncOptions:
    - CreateNamespace=false
    automated:
      selfHeal: true
      prune: true